Areas/TravelAdmin/Controllers/AdminTopController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using Travel_MVC.Models;

namespace Travel_MVC.Areas.TravelAdmin.Controllers
{
    public class AdminTopController : Controller
    {

        TravelDB DB = new TravelDB ();
        // GET: TravelAdmin/AdminTop
        public ActionResult Index()
        {
            return View(DB.TopSliders.ToList());
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(TopSlider slider,HttpPostedFileBase SliderPhoto)
        {//Şəkil əlavə etmə hissəsi bu formada yazilaraq elave edilir
            if (ModelState.IsValid) {

                if (SliderPhoto != null)
                {
                    if (SliderPhoto != null)
                    {
                        if (SliderPhoto.ContentLength > 0)
                        {
                            if (
                             SliderPhoto.ContentType.ToLower() == "image/jpg" ||
                             SliderPhoto.ContentType.ToLower() == "image/png" ||
                             SliderPhoto.ContentType.ToLower() == "image/gif" ||
                             SliderPhoto.ContentType.ToLower() == "image/bmp" ||
                             SliderPhoto.ContentType.ToLower() == "image/jpeg" 
                             ){
                                WebImage img = new WebImage(SliderPhoto.InputStream);//WebImage using
                                FileInfo flInfo = new FileInfo(SliderPhoto.FileName);//FileInfo using
                                string fileName = "Slider" + Guid.NewGuid() + flInfo.Extension;
                                img.Save("~/Upload/SliderPhoto/" + fileName);
                                slider.SliderPhoto = "/Upload/SliderPhoto/" + fileName;
                               
                            }
                        }
                    }
                }
                DB.TopSliders.Add(slider);
                DB.SaveChanges();

                return RedirectToAction("index");
            }
            return View();
        }

        public ActionResult Edit(int? id)
        {
            if (id == null) return HttpNotFound();
            TopSlider selectedSlider = DB.TopSliders.FirstOrDefault(tp => tp.id == id);
            if (selectedSlider == null) return HttpNotFound();
            return View(selectedSlider);
        }
        [HttpPost]
        public ActionResult Edit(int? id, TopSlider slider)
        {
            if (ModelState.IsValid)
            {
                TopSlider selectedSlider = DB.TopSliders.FirstOrDefault(tp => tp.id == id);
                selectedSlider.Header = slider.Header;
                selectedSlider.Description = slider.Description;
                selectedSlider.SliderPhoto = slider.SliderPhoto;
                DB.SaveChanges();
                return RedirectToAction("index");
            }

            return View();
        }
        // GET: TravelAdmin/AdminDiscoverLefts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TopSlider topSlider = DB.TopSliders.Find(id);
            if (topSlider == null)
            {
                return HttpNotFound();
            }
            return View(topSlider);
        }

        // POST: TravelAdmin/AdminDiscoverLefts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TopSlider topSlider = DB.TopSliders.Find(id);
            DB.TopSliders.Remove(topSlider);
            DB.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

Areas/TravelAdmin/Views/AdminTop/Create.cshtml
@model Travel_MVC.Models.TopSlider

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/TravelAdmin/Views/Shared/_Layout1.cshtml";
}

<h2>Create</h2>

<form action="" method="post" enctype="multipart/form-data">
    @Html.AntiForgeryToken()



    <div class="form-horizontal">
        <h4>TopSlider</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.SliderPhoto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="SliderPhoto" />
                @Html.ValidationMessageFor(model => model.SliderPhoto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Header, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Header, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Header, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </div>
    </div>
</form>

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Areas/TravelAdmin/Views/AdminTop/Delete.cshtml
@model Travel_MVC.Models.TopSlider

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/TravelAdmin/Views/Shared/_Layout1.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TopSlider</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.SliderPhoto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SliderPhoto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Header)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Header)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Areas/TravelAdmin/Views/AdminTop/Edit.cshtml
@model Travel_MVC.Models.TopSlider

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/TravelAdmin/Views/Shared/_Layout1.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TopSlider</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.SliderPhoto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SliderPhoto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SliderPhoto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Header, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Header, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Header, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Areas/TravelAdmin/Views/AdminTop/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/TravelAdmin/Views/Shared/_Layout1.cshtml";
}

@model  IList<Travel_MVC.Models.TopSlider>

    <p class="btn btn-outline-success">
        <a href="@Url.Action("Create","AdminTop")">Create</a>
    </p>
    <table class="table table-bordered">
        
        <thead>
            <tr>
                <th>Sekil</th>
                <th>Basliq</th>
                <th>Melumat</th>

            </tr>
        </thead>
        <tbody>

            @foreach (var tp in Model)
            {
                <tr>
                    <td style="width:25%">
                        <img class="img-fluid" src="@tp.SliderPhoto" />
                    </td>
                    <td>@tp.Header</td>
                    <td>@tp.Description</td>
                    <td>
                        <a href="@Url.Action("Edit","AdminTop", new {id=tp.id})">Edit</a>|
                        <a href="@Url.Action("Delete","AdminTop")">Delete</a>    
                    </td>
                </tr>

            }
        </tbody>
    </table>